### ISSUE TITLE
Create a basic interface

### ISSUE THREAD

**Issue by Turchanov-Denis** [Querang/DeKi-Project#4]
- Buttons: "add command", "do command", "switch mode", "activate/disable voice"
- Make dialog window
- Make character for program (early design)

**Comment by NikMatyukhin** [comment]
Для того, чтобы сделать фон прозрачным. По крайней мере, что-то из этого.
```python
pixmap = QPixmap("путь/до/вашей/картинки.png", "r")
pixmap = pixmap.scaled(400, 630)
self.setPixmap(pixmap)
self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
self.setStyleSheet('QLabel{background-color: rgba(255, 255, 255, 0);}')
self.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.FramelessWindowHint)
```

**Comment by NikMatyukhin** [comment]
Для перемещения окна с флагом FramelessWindowHint необходимо переопределить mouseClickEvent, mouseMoveEvent и т.п. события мыши на главном окне.
